#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <time.h>

/* To be compiled with:
gcc project-euler-002.c -Wall -Wextra -Werror -O3 -std=c2x -pedantic -o project-euler-002 */

/* Project Euler 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: ; ; ; ;
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  ; ; ; ;
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. ; ; ; ;
https://projecteuler.net/problem=2 */

int project_euler_2 (void) {
  uint64_t f1 = 1;
  uint64_t f2 = 2;
  uint64_t sum = 2;
  uint64_t tmp = 0;
  while (f2 <= 4000000) {
    tmp = f2;
    f2 = f1 + f2;
    f1 = tmp;
    if (f2 % 2 == 0) {
      sum += f2;
    }
  }
  printf("Solution: %llu\n", sum);
  return EXIT_SUCCESS;
}

int main(int argc, [[maybe_unused]] char* argv[argc+1]) {
  struct timespec start, end;
  double duration;
  clock_gettime(CLOCK_MONOTONIC, &start);

  project_euler_2();

  clock_gettime(CLOCK_MONOTONIC, &end);
  duration = (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1e9;
  printf("Duration: %f seconds\n", duration);
  return EXIT_SUCCESS;
}

// end
